name: Nano armor
# Никнейм в Telegram
author: "@pipline_sh"
# Описание таска на платформе.
description: | 
  `@pipline_sh`

  О нет! Ящеры разработали новую квантовую броню, которая способна изменять свои свойства в зависимости от переданной ей команды! Однако не были бы они ящерами, если бы не допустили ошибки при проектировании...

# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: pwn
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
connection_info: nc tasks.ctf.vrnctf.ru 13577

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{try_t0_f1nd_3x4pt10n}",
    data: "case_insensitive",
  }


# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
   - public/task.zip

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"

