/**
 * @fileoverview gRPC-Web generated client stub for main
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.main = require('./service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.main.WatermarkServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.main.WatermarkServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.AddWatermarkRequest,
 *   !proto.main.AddWatermarkResponse>}
 */
const methodDescriptor_WatermarkService_AddWatermark = new grpc.web.MethodDescriptor(
  '/main.WatermarkService/AddWatermark',
  grpc.web.MethodType.UNARY,
  proto.main.AddWatermarkRequest,
  proto.main.AddWatermarkResponse,
  /**
   * @param {!proto.main.AddWatermarkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.AddWatermarkResponse.deserializeBinary
);


/**
 * @param {!proto.main.AddWatermarkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.AddWatermarkResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.AddWatermarkResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.WatermarkServiceClient.prototype.addWatermark =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.WatermarkService/AddWatermark',
      request,
      metadata || {},
      methodDescriptor_WatermarkService_AddWatermark,
      callback);
};


/**
 * @param {!proto.main.AddWatermarkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.AddWatermarkResponse>}
 *     Promise that resolves to the response
 */
proto.main.WatermarkServicePromiseClient.prototype.addWatermark =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.WatermarkService/AddWatermark',
      request,
      metadata || {},
      methodDescriptor_WatermarkService_AddWatermark);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.Command,
 *   !proto.main.CommandResponse>}
 */
const methodDescriptor_WatermarkService_ExploitMe = new grpc.web.MethodDescriptor(
  '/main.WatermarkService/ExploitMe',
  grpc.web.MethodType.UNARY,
  proto.main.Command,
  proto.main.CommandResponse,
  /**
   * @param {!proto.main.Command} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.CommandResponse.deserializeBinary
);


/**
 * @param {!proto.main.Command} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.CommandResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.CommandResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.WatermarkServiceClient.prototype.exploitMe =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.WatermarkService/ExploitMe',
      request,
      metadata || {},
      methodDescriptor_WatermarkService_ExploitMe,
      callback);
};


/**
 * @param {!proto.main.Command} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.CommandResponse>}
 *     Promise that resolves to the response
 */
proto.main.WatermarkServicePromiseClient.prototype.exploitMe =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.WatermarkService/ExploitMe',
      request,
      metadata || {},
      methodDescriptor_WatermarkService_ExploitMe);
};


module.exports = proto.main;

