version: '3.7'
name: garbage_rpc
services:
    app:
        build: .
        ports:
            - "8080:8080"
    web:
        build: web/
        ports:
            - "3000:3000"
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - "81:80"
        depends_on:
            - web
            - app
