# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать 

# Обязательные поля
# Имя задачи на CTFd
name: Three bogatyrs
# Никнейм в Telegram
author: "@kotz1k"
# Описание таска на платформе.
description: | 
  `@kotz1k`

  Отправились как-то три ловких и хитрых руса на разведку в стан ящеров окаянных. Долго их не было,
  и вот, когда надежда на их возвращение была потеряна, они вернулись. Каждый из них нес по одному из артефактов ящеров.
  Каждый из артефактов хранил в себе кусочек очень важной информации - пароля, открывающего дверь в любой из городов ящеров.
  К вам обратились как к самому лучше русу, который обладает искусством форензики заморской. Помогите разгадать пароль.
# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: forensic
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{1_l0v3_c4bb463}",
    data: "case_insensitive",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
  - public/logs.txt
  - public/MyClass.class
  - public/python-obf.py

# Подсказки. Можно передавать словари и строки
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"