name: Baikal water
# Никнейм в Telegram
author: "@Ichinichi"
# Описание таска на платформе.
description: | 
  `@Ichinichi`

  Услышав о чудотворных свойствах байкальской воды Радислав решил наведаться на базар, но с покупкой возникли трудности...

# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: web
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
connection_info: https://baikal.tasks.ctf.vrnctf.ru

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{b357_w473r_1n_7h3_w0rld}",
    data: "case_insensitive",
  }


# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"