name: Enemy file
# Никнейм в Telegram
author: "@Ichinichi"
# Описание таска на платформе.
description: | 
  `@Ichinichi`

  Благодаря новейшим технологиям (дубинкой по башке) был совершен перехват важнейших данных Ящеров. Но вот беда, внутри секретных документов не оказалось ничего секретного.
  Помогите Русам распутать эту загадку.

# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: stegano
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: https://baikal.tasks.ctf.vrnctf.ru

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{z1p_h34d3r5}",
    data: "case_insensitive",
  }


# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
  - public/file
# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"