# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать 

# Обязательные поля
# Имя задачи на CTFd
name: Rus-traveler
# Никнейм в Telegram
author: "@jim_amlt"
# Описание таска на платформе.
description: | 
  `@jim_amlt`

  Богатырь Радислав после тяжкой битвы с ящерами отправился на источники целебные. Но его соратники сомневаются, не подменили ли ящеры богатыря великого на источниках целебных? Помогите богатырям определить город, в котором "отдыхал" богатырь Радислав.
  
  [Фотография с отдыха](https://sun1-97.userapi.com/impg/LrP2mX4IN7mmrQLxsvVr7CorqYOGkRRNih79yg/k3cyvbsB3f8.jpg?size=1954x1141&quality=96&sign=dcd061ea3eee91940d7927052c0de9e8&c_uniq_tag=unf5XOvCAGyw6dMmz8c7PqDkyQ4uOTnmFnJuq7ZYmPA&type=album)

  *Формат флага: vrnctf{Gorod}*
# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: osint
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  # Флаг можно задать так
  - vrnctf{Kitaibaraki}
  # То же что и первый вариант, только подробнее
  # - {
  #   type: "static",
  #   content: "flag{wat}",
  # }
  # Нечувствительный к регистру флаг
  # - {
  #   type: "static",
  #   content: "flag{wat}",
  #   data: "case_insensitive",
  # }
  # Нечувствительный к регистру флаг, заданный регулярным выражением
  # - {
  #   type: "regex",
  #   content: "(.*)STUFF(.*)",
  #   data: "case_insensitive",
  # }

# Примечания для админов, не видны участникам
# Разрешены строки

topics:
  # - НЕ ЗАБЫТЬ ОТКРЫТЬ ПОСТЫ
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/task.zip

# Подсказки. Можно передавать словари и строки
# hints:
#     - Гугл/яндекс картинки

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"