# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать 

# Обязательные поля
# Имя задачи на CTFd
name: Traitor
# Никнейм в Telegram
author: "@jim_amlt"
# Описание таска на платформе.
description: | 
  `@jim_amlt`

  К богатырям поступила информация, что кто-то предал их! Предатель помогает ящерам и воспользовался своим именем, чтобы помочь ящерам замаскировать свое оружие. Богатыри узнали, что оружие ящеров было обнаружено 2 ноября 2022 года, а также в названии содержало "Ангар"/"Angar".

  *Формат флага vrnctf{Name_Surname}*
# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: osint
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  # Флаг можно задать так
  - vrnctf{Rostislav_Pobedin}
  # То же что и первый вариант, только подробнее
  # - {
  #   type: "static",
  #   content: "flag{wat}",
  # }
  # Нечувствительный к регистру флаг
  # - {
  #   type: "static",
  #   content: "flag{wat}",
  #   data: "case_insensitive",
  # }
  # Нечувствительный к регистру флаг, заданный регулярным выражением
  # - {
  #   type: "regex",
  #   content: "(.*)STUFF(.*)",
  #   data: "case_insensitive",
  # }

# Примечания для админов, не видны участникам
# Разрешены строки

topics:
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/task.zip

# Подсказки. Можно передавать словари и строки
# hints:
#     - https://app.any.run/
#     - https://www.virustotal.com/gui/home/search
#     - https://app.any.run/tasks/9c5a4006-f28e-4787-a04c-9f252c494576/


# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"